stages:
  - test
  - release
  - deploy

before_script:
  - npm install -g expo-cli
  - npm install
  - npm install typescript

node:20.9.0:
  image: node:20.9.0
  stage: test
  allow_failure: true
  only:
    - branches
  script:
    - npx expo-doctor

bump-version:
  image: node:20.9.0
  stage: release
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_AUTHOR !~ /semantic-release-bot.*/)
  script:
    - "which ssh-agent || ( apk --update add openssh-client git )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$CI_SSH_KEY")
    - npx semantic-release

deploy_to_github:
  image: node:20.9.0
  stage: deploy
  script:
    - git clone https://$GITHUB_USER:$GITHUB_TOKEN@github.com/RealTranslate.git
    - cd RealTranslate
    - touch gitlab-deploy-info.txt
    - echo "User; $GITHUB_USER Fecha; $(date)" > gitlab-deploy-info.txt
    - git add gitlab-deploy-info.txt
    - git commit -m "GitLab Deploy $(date)"
    - git push origin master

publish:
  image: node:20.9.0
  stage: release
  environment:
    name: production
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v.*$/
  before_script:
    - apk --update add git
    - npm install -g expo-cli eas-cli
    - npm install
  script:
    - eas build --platform android --profile production --non-interactive --auto-submit